In [14]:
import pandas as pd

In [ ]:
internacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Internacional fijo')
internacional

In [ ]:
nacional = pd.read_excel('/Users/matias/Library/CloudStorage/GoogleDrive-mvilla@buenavistacapital.com/.shortcut-targets-by-id/1Lbjcks5sDTC17AftNR6mDxW8bwAA7EaA/BVC/Matias V/Ranking Fondos/Data.xlsx', sheet_name='Nacional fijo')
nacional

,Dates,AACCHIA CI Equity,CCHIACB CI Equity,CELFFIB CI EQUITY,CFIMPIO CI EQUITY,CFIQAC CI EQUITY,ECH US EQUITY,FALCTNV CI EQUITY,MBIARANV CI EQUITY,TCHIEQB CI EQUITY,...,MODUECH CI EQUITY,MRCLP CI EQUITY,IPSA Index,FIQRLSA CI Equity,FCFIANV CI Equity,IMTDECI CI Equity,MODECHD CI Equity,DEUCORP CI Equity,CFIETFCC CC Equity,MBIDTANV CI Equity
0,2007-01-01,NaN,NaN,33239.7839,2743.7330,NaN,NaN,NaN,24952.7896,NaN,...,NaN,NaN,2693.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,33250.4300,2739.2791,NaN,NaN,NaN,24965.0939,NaN,...,NaN,NaN,2689.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,33408.7278,2751.5267,NaN,NaN,NaN,24926.1817,NaN,...,NaN,NaN,2725.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,33391.5505,2761.7548,NaN,NaN,NaN,25060.9742,NaN,...,NaN,NaN,2738.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,33342.5164,2777.6091,NaN,NaN,NaN,24952.7931,NaN,...,NaN,NaN,2723.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4897,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16214.32,1765.3515,1752.3660,1532.2225,49857.8898,1517.596,17244.4447
4898,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16206.27,1763.8071,1750.5294,1531.0770,49812.6349,1517.081,17229.4921
4899,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16212.61,1763.9592,1751.7193,1531.2919,49828.3057,1517.699,17240.0191
4900,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16217.79,1764.5898,1752.3001,1531.6712,49842.6832,1518.111,17245.4492
4901,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16217.79,1764.5898,1752.3001,1531.6712,49842.6832,1517.596,17245.4492

In [ ]:
df_final = pd.merge(internacional, nacional, how = 'left', on = 'Dates')
df_final = df_final.dropna(axis=1, how='all')
df_final

,Dates,0JKT LN Equity,AAXJ US Equity,ABCHNSA LX EQUITY,BGFPABA LN EQUITY,CPXJ LN EQUITY,CAFINIV LX EQUITY,FFASAIU LX EQUITY,FFEMASI LX EQUITY,FIASCIU LX EQUITY,...,MODUECH CI EQUITY,MRCLP CI EQUITY,IPSA Index,FIQRLSA CI Equity,FCFIANV CI Equity,IMTDECI CI Equity,MODECHD CI Equity,DEUCORP CI Equity,CFIETFCC CC Equity,MBIDTANV CI Equity
0,2007-01-01,NaN,NaN,NaN,4.13102,NaN,124.47,NaN,NaN,NaN,...,NaN,NaN,2693.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-02,NaN,NaN,NaN,4.17635,NaN,125.69,NaN,NaN,NaN,...,NaN,NaN,2689.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-03,NaN,NaN,NaN,4.11882,NaN,126.26,NaN,NaN,NaN,...,NaN,NaN,2725.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-04,NaN,NaN,NaN,4.03831,NaN,125.45,NaN,NaN,NaN,...,NaN,NaN,2738.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-05,NaN,NaN,NaN,4.05409,NaN,124.76,NaN,NaN,NaN,...,NaN,NaN,2723.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,2025-09-23,33.03644,123.6590,131.11,20.03812,218.43,501.81,16.27,28.47,23.56,...,1898.7715,20871.156,9146.80,16116.28,1757.6365,1745.0538,1527.0008,49625.6107,1513.372,17163.2542
4887,2025-09-24,33.03644,123.2522,132.59,19.98974,215.84,499.77,16.18,28.50,23.52,...,1898.0130,20867.343,9114.79,16111.24,1756.6948,1744.3139,1526.3732,49595.2662,1511.723,17159.1192
4888,2025-09-25,33.03644,122.8318,133.13,19.88845,214.68,496.91,16.11,28.29,23.42,...,1898.0914,20882.300,9040.46,16110.98,1756.5987,1743.8363,1526.4185,49587.1809,1512.959,17151.8829
4889,2025-09-26,33.03644,122.1266,131.31,19.76205,215.89,492.63,16.07,27.95,23.31,...,1899.4228,20871.407,9023.05,16140.02,1758.3600,1745.4285,1527.4716,49678.9190,1511.723,17169.2268
4890,2025-09-29,33.03644,123.3200,131.31,19.91817,218.27,492.63,16.09,28.37,23.43,...,1899.7732,20898.640,8996.57,16151.75,1760.4616,1747.5861,1528.8897,49726.2951,1513.268,17183.7091

In [ ]:
df_final.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_prices.csv')

In [ ]:
diccionario = pd.read_excel('dict_temp_full_portfolio.xlsx')
diccionario.to_csv('/Users/matias/Desktop/Proyectos/ranking-fondos/data/funds_dictionary.csv')